# Generated by Django 3.0.4 on 2023-12-14 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=100)),
                ('password', models.CharField(default='Unknown', max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='O', max_length=1)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('B+', 'B Positive'), ('O+', 'O Positive'), ('AB+', 'Ab Positive'), ('A-', 'A Negative'), ('B-', 'B Negative'), ('O-', 'O Negative'), ('AB-', 'Ab Negative'), ('UKN', 'Unknown')], default='UKN', max_length=3)),
                ('medical_history', models.CharField(default='Unknown', max_length=500)),
            ],
        ),
    ]
